/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AdminSecretRouteImport } from './routes/admin-secret'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupPatientRouteImport } from './routes/signup.patient'
import { Route as SignupHospitalRouteImport } from './routes/signup.hospital'
import { Route as SignupDoctorRouteImport } from './routes/signup.doctor'
import { Route as DashboardPatientRouteImport } from './routes/dashboard.patient'
import { Route as DashboardDoctorRouteImport } from './routes/dashboard.doctor'
import { Route as ApiAnalyzeRouteImport } from './routes/api.analyze'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecretRoute = AdminSecretRouteImport.update({
  id: '/admin-secret',
  path: '/admin-secret',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPatientRoute = SignupPatientRouteImport.update({
  id: '/signup/patient',
  path: '/signup/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupHospitalRoute = SignupHospitalRouteImport.update({
  id: '/signup/hospital',
  path: '/signup/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupDoctorRoute = SignupDoctorRouteImport.update({
  id: '/signup/doctor',
  path: '/signup/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPatientRoute = DashboardPatientRouteImport.update({
  id: '/dashboard/patient',
  path: '/dashboard/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDoctorRoute = DashboardDoctorRouteImport.update({
  id: '/dashboard/doctor',
  path: '/dashboard/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-secret': typeof AdminSecretRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/signup/doctor': typeof SignupDoctorRoute
  '/signup/hospital': typeof SignupHospitalRoute
  '/signup/patient': typeof SignupPatientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-secret': typeof AdminSecretRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/signup/doctor': typeof SignupDoctorRoute
  '/signup/hospital': typeof SignupHospitalRoute
  '/signup/patient': typeof SignupPatientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-secret': typeof AdminSecretRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/signup/doctor': typeof SignupDoctorRoute
  '/signup/hospital': typeof SignupHospitalRoute
  '/signup/patient': typeof SignupPatientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-secret'
    | '/demo'
    | '/login'
    | '/api/analyze'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/signup/doctor'
    | '/signup/hospital'
    | '/signup/patient'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-secret'
    | '/demo'
    | '/login'
    | '/api/analyze'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/signup/doctor'
    | '/signup/hospital'
    | '/signup/patient'
  id:
    | '__root__'
    | '/'
    | '/admin-secret'
    | '/demo'
    | '/login'
    | '/api/analyze'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/signup/doctor'
    | '/signup/hospital'
    | '/signup/patient'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSecretRoute: typeof AdminSecretRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  DashboardDoctorRoute: typeof DashboardDoctorRoute
  DashboardPatientRoute: typeof DashboardPatientRoute
  SignupDoctorRoute: typeof SignupDoctorRoute
  SignupHospitalRoute: typeof SignupHospitalRoute
  SignupPatientRoute: typeof SignupPatientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-secret': {
      id: '/admin-secret'
      path: '/admin-secret'
      fullPath: '/admin-secret'
      preLoaderRoute: typeof AdminSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/patient': {
      id: '/signup/patient'
      path: '/signup/patient'
      fullPath: '/signup/patient'
      preLoaderRoute: typeof SignupPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/hospital': {
      id: '/signup/hospital'
      path: '/signup/hospital'
      fullPath: '/signup/hospital'
      preLoaderRoute: typeof SignupHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/doctor': {
      id: '/signup/doctor'
      path: '/signup/doctor'
      fullPath: '/signup/doctor'
      preLoaderRoute: typeof SignupDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/patient': {
      id: '/dashboard/patient'
      path: '/dashboard/patient'
      fullPath: '/dashboard/patient'
      preLoaderRoute: typeof DashboardPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/doctor': {
      id: '/dashboard/doctor'
      path: '/dashboard/doctor'
      fullPath: '/dashboard/doctor'
      preLoaderRoute: typeof DashboardDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSecretRoute: AdminSecretRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  DashboardDoctorRoute: DashboardDoctorRoute,
  DashboardPatientRoute: DashboardPatientRoute,
  SignupDoctorRoute: SignupDoctorRoute,
  SignupHospitalRoute: SignupHospitalRoute,
  SignupPatientRoute: SignupPatientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
